server:
  port: 8080


spring:
  profiles:
    active: dev
  application:
    name: talias-web-management

  #数据库连接信息
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tilias
      username: root
      password: 123

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    #mybatis日志输出
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

tilias:
  aliyun:
    endpoint: ${tilias.aliyun.endpoint}
    bucket-name: ${tilias.aliyun.bucket-name}
    region: ${tilias.aliyun.region}
    access-key-id: ${tilias.aliyun.access-key-id}
    access-key-secret: ${tilias.aliyun.access-key-secret}

